version: "2"
services:
  app:
    image: haritkumar/react-app:latest
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - ackee
  ackee:
    image: haritkumar/ackee:2.1.0
    restart: always
    ports:
      - "5000:5000"
    environment:
      - WAIT_HOSTS=mongo:27017
      - ACKEE_MONGODB=mongodb://mongo:27017/ackee
      - ACKEE_PORT=5000
      - ACKEE_USERNAME=admin
      - ACKEE_PASSWORD=admin
      - ACKEE_ALLOW_ORIGIN="*"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db